spring:
  application:
    name: eureka-cluster-server
  profiles:
    peer1

server:
  port: 8761

eureka:
  instance:
    #主机名，必填
    hostname: prayer1.com
  client:
    #register-with-eureka 默认值为true，即将自己注册到eureka中
    #fetch-registry 默认值为true，即从别的eureka节点获取注册信息，不用修改
    service-url:
      #此节点应向其他节点发起请求
      defaultZone: http://prayer2.com:8762/eureka/,http://prayer3.com:8763/eureka/

management:
  endpoint:
    shutdown:
      enabled: true