spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    appname: aha-eureka
#    hostname: prayer1.com
  client:
    #是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    #register-with-eureka: false
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    #fetch-registry: false
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://prayer1.com:8761/eureka/